inputs:
  data: /home/mdicosta/hf_pid_studies/seldatasets/pbpb/data/LHC23zzh_pass4_small_k0s.parquet
  mc: /home/mdicosta/hf_pid_studies/seldatasets/pbpb/mc/LHC24g2_medium_k0s.parquet

mother_mass_var_name: fMassK0
mother_pt_var_name: fPt
variables_to_plot: [fNSigmaTpcPosPi, fNSigmaTpcNegPi, fNSigmaTofPosPi, fNSigmaTofNegPi]
dau_names: [pos_pi, neg_pi]
dau_pt_var_names: [fPtPos, fPtNeg] # relative to the variables_to_plot
mass_range: [0.425, 0.575]
fit_config:
  bkg_func: chebpol1
  mean: 0.5
  sigma: 0.01
  nl: 10
  nr: 10
  alphal: 1.
  alphar: 1.
max_workers: 2
pt_bins: [0.4, 0.8, 1.2, 1.6] #, 2.0, 5.0] #, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.5, 2.0, 4.0]
cent_bins: [
            # [0, 20], 
            [20, 40], 
            [40, 60], 
            # [60, 80], 
            # [0, 50], 
            # [0, 50],  
            # [60, 80], 
            # [50, 60], 
            # [60, 70], 
            # [70, 80] 
            # [50, 100], 
            # [40, 50], 
            # [50, 60] 
           ]
occ_bins: [ 
            [0, 20000], 
            [0, 40000], 
            [0, 99999999], 
            # [40000, 99999999] 
            # [60000, 70000], 
            # [70000, 80000], 
            # [80000, 90000],  
            # [90000, 100000],  
            # [2000, 4000], 
            # [4000, 99999] 
          ]

output:
  dir: distributions/k0s/pbpb/